name: 'Deploy to staging'
on :
  push:
    branches:
      dev
jobs:
  name: build the application
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v4
      uses: actions/setup-node@v3
      with:
        node-version: "18"
      run : npm ci
      run : npm run start